### ISSUE TITLE
Create email and password recovery fields for accounts.

### ISSUE THREAD

**Issue by brekt** [wbeck32/road-warrior#13]
Consider OAuth, Passport, etc.

**Comment by rdubrock** [comment]
I think this is going to require setting up an SMTP server. Lets check out this:
http://www.andreagrandi.it/2014/08/31/getting-started-with-digital-ocean-vps-configuring-dns-and-postfix-for-email-forwarding/
and this:
https://github.com/andris9/smtp-server

**Comment by rdubrock** [comment]
Also Haraka looks cool: https://haraka.github.io/manual/Body.html

**Comment by rdubrock** [comment]
Done!
